---
# roles/ssh_pqc/tasks/main.yml

- name: Vérifier la distribution
  ansible.builtin.debug:
    msg: "Distribution détectée : {{ ansible_distribution }} {{ ansible_distribution_version }}"

- name: Installer OpenSSH sur Debian
  ansible.builtin.include_tasks:
    file: debian.yml
  when: ansible_os_family == "Debian"

- name: Installer OpenSSH sur Red Hat
  ansible.builtin.include_tasks:
    file: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Récupérer la version OpenSSH
  ansible.builtin.command:
    cmd: ssh -V
  register: openssh_version
  changed_when: false
  failed_when: false

- name: Afficher la version OpenSSH
  ansible.builtin.debug:
    var: openssh_version.stderr

- name: Déployer la configuration PQC
  ansible.builtin.template:
    src: sshd_config.d/99-pqc.conf.j2
    dest: /etc/ssh/sshd_config.d/99-pqc.conf
    owner: root
    group: root
    mode: "0644"
    validate: "/usr/sbin/sshd -t -f %s"
  notify: Restart ssh
